# Generated by Django 4.2.16 on 2024-11-17 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_rename_productos_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
    ]
